services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    env_file:
      - ../.env
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"     # grpc
      - "4318:4318"     # http
      - "13133:13133"   # health
    restart: unless-stopped